pipelines:
  visual-files:
    group: common
    label_template: "${COUNT}"
    materials:
      visual-files-git:
        git: https://github.com/ukparliament/uk.parliament-visual-files.git
        branch: master
        auto_update: true
    stages:
      - deploy:
          jobs:
            deploy:
              tasks:
                - exec:
                    run_if: passed
                    command: make
                    arguments:
                      - deploy_to_release


environments:
  WebDEVCI:
    pipelines:
      - visual-files
